language: bash
services: docker

env:
  - VARIANT=7.0/fpm
  - VARIANT=7.0/fpm-alpine
  - VARIANT=7.0/cli
  - VARIANT=7.1/fpm
  - VARIANT=7.1/fpm-alpine
  - VARIANT=7.1/cli
  - VARIANT=7.2/fpm
  - VARIANT=7.2/fpm-alpine
  - VARIANT=7.2/cli

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash
  - cd "$VARIANT"
  - slash='/'; image="wordpress:${VARIANT//$slash/-}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image" .
      ~/official-images/test/run.sh "$image"
    )

after_script:
  - docker images

# vim:set et ts=2 sw=2:
