language: bash
services: docker
dist: xenial

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - bash ./build.sh 

after_script:
  - docker images

# vim:set et ts=2 sw=2:
